### ISSUE TITLE
[suggestion] changing crosshair color when mob is in range

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Crendgrim/DynamicCrosshair#38]
Not sure if this would be too cheaty but basically if a mob gets within attack range the crosshair would change to a red color (or whatever color the player chooses)

**Comment by Crendgrim** [comment]
This is a good suggestion. I don't think it is cheaty, since the vanilla attack indicator also shows up under those conditions.

Note on this: it should probably take the colour from the "targeted entity" crosshair, even if a weapon crosshair is displayed. Will have to see how to implement this the best way.
