### ISSUE TITLE
Shovel Not Marked as "Correct" Tool for Grass Path Blocks

### ISSUE THREAD

**Issue by jetblackrx89** [Crendgrim/DynamicCrosshair#53]
As title states, the shovel doesn't show the "correct tool" crosshair for grass path blocks, even though it is and mines them faster than any other tool. I didn't see a place to manually configure it and assume this is a bug. This is on 1.19.4.

**Comment by Crendgrim** [comment]
Assuming you mean the block you get when right-clicking with a shovel on dirt or grass, that shows the correct tool crosshair for me. Do you have any other mods installed? Or is the grass path block something else?

**Comment by Crendgrim** [comment]
Your video doesn't work for me, it's all black.

If you have not changed the default configuration, then the rounded bracket around the crosshair means "usable / interactable". It is shown on grass before because you can convert it to a path block, and would also be shown on chests etc. The "correct tool" crosshair is the dot (correct tool) or cross (incorrect tool) within the square.

If you have changed the configuration, could you upload it?

**Comment by Crendgrim** [comment]
Yep! The idea is that it will always show when you can right-click. I think the only exception is the shield crosshair.
