### ISSUE TITLE
spyglass astronomy compat ... or help with configs

### ISSUE THREAD

**Issue by dadoirie** [Crendgrim/DynamicCrosshair#55]
Would love to see a compat to [Spyglass Astronomy](https://www.curseforge.com/minecraft/mc-mods/spyglass-astronomy) 

meanwhile I'm trying following settings with advanced dynamical crosshair hiding but still the crosshair doesn't show up when looking through the spyglass

![image](https://github.com/Crendgrim/DynamicCrosshair/assets/61109153/97420254-61e3-4edb-8846-abd34c635961)
![image](https://github.com/Crendgrim/DynamicCrosshair/assets/61109153/ba3ab792-704b-4b78-a362-117fb76c8b70)

no crosshair
![image](https://github.com/Crendgrim/DynamicCrosshair/assets/61109153/0b81463c-c44e-4769-a9c2-7221df996129)

how do I make the crosshair appear when looking through the spyglass?

**Comment by Crendgrim** [comment]
Sorry for the late reply, I understood too late what the problem was here. Clearly it is not obvious enough, but it's "fixed" by being clearer in modern versions. You should input the additional items without the quotes, so `minecraft:spyglass` rather than `"minecraft:spyglass"`.

That said, I will likely add a dedicated option to always show a crosshair with spyglasses, as that seems like something useful in other contexts too. Keeping this issue open to track that.

**Comment by Crendgrim** [comment]
Added said option in 7.0.4
