### ISSUE TITLE
Lol. Your mod is causing a crash with Mythic Mounts.

### ISSUE THREAD

**Issue by TheButterbrotMan** [Crendgrim/DynamicCrosshair#8]
https://bytebin.lucko.me/yvtmRcmu5B

**Comment by TheButterbrotMan** [comment]
https://github.com/TheButterbrotMan/Deathdusk/issues/103#issuecomment-1146812534

**Comment by Crendgrim** [comment]
This is a bug in Mythic Mounts.

They force-cast `class net.minecraft.class_638` (yarn mapping: `ClientWorld`) to `class net.minecraft.class_3218` (yarn mapping: `ServerWorld`), without checking if they are server side. That is what I can see from the crash log alone.

In vanilla, `isBreedingItem()` is a very simple check, but they likely checked in the one place it gets called from the client. That's why it doesn't crash without my mod. After a cursory check of the byte code, it doesn't even look like they would need the cast, but I'm not entirely sure on that.

As Mythic Mounts is closed source, I cannot send a patch request, so please report this bug to the authors.

For the time being, I can force-patch it out to stop the crashes.
